### ISSUE TITLE
Publish to bower/npm

### ISSUE THREAD

**Issue by weichensw** [hammerjs/simulator#4]
It seems this is not published to npm/bower.

**Comment by amercier** [comment]
+1. Also, please `git tag` so users can do something like:

```
"hammerjs-simulator": "^0.1.0",
```

in our respective `bower.json`.

**Comment by eightypop** [comment]
:+1:

**Comment by revolunet** [comment]
yes please

**Comment by tregusti** [comment]
+1

**Comment by brancusi** [comment]
+1

**Comment by jtangelder** [comment]
Sorry, I will publish it to npm today :-)

**Comment by jtangelder** [comment]
https://www.npmjs.com/package/hammer-simulator
